Check if game results have been changed.

diff --git a/mktable b/mktable
--- a/mktable
+++ b/mktable
@@ -9,14 +9,19 @@ git checkout master
 ./tour-parse > $results
 git add $results
 git commit -m "Update game results."
+# Successful `git commit' returns exit code `0'
+ret_code=$?
 
-# Update the tournament table
-bin/lorchess > temp_table.html
-git checkout gh-pages
-mv temp_table.html $table
-git add $table
-git commit -m "Update the tournament table."
-git checkout master
+if [[ $ret_code == 0 ]]; then
 
-# Check the difference between game results
-git diff HEAD^ HEAD -- $results
+    # Update the tournament table
+    bin/lorchess > temp_table.html
+    git checkout gh-pages
+    mv temp_table.html $table
+    git add $table
+    git commit -m "Update the tournament table."
+    git checkout master
+
+    # Check the difference between game results
+    git diff HEAD^ HEAD -- $results
+fi
